[package]
name = "mash"
version = "0.1.0"
entrypoint = "src/lib.typ"
author = ["Brian Pickens <@physgun>"]
license = "Apache-2.0 OR MIT"
compiler = "0.13.1"
repository = "https://github.com/physgun/mash"
description = "Vividly illustrate layouts for keyboards and other input devices, with CeTZ."
exclude = [".gitignore"]
categories = ["visualization"]
keywords = ["keyboard", "layout"]